### ISSUE TITLE
Add custom rules

### ISSUE THREAD

**Issue by felipe-norato** [Quramy/storybook-angular-cli-helper#1]
We can add to `applyAngularCliConfig` one more parameter for custom rules.
Today I installed this package and I had to push each rule.
I tried to submit a PR, but this repo cannot allow it.
My idea:
```js
export function applyAngularCliConfig(config: any, customRules: Array<any>=[]) {
# code goes here
  config.module.rules = [
    ...cliStyleConfig.module.rules,
    ...styleRules,
    ...customRules
  ];
}
```

**Comment by Quramy** [comment]
@noratodaitan Thanks your feedback :smile:
Today, this function merged into original Storybook repo ( https://github.com/storybooks/storybook/pull/2735 ).
And you can set your custom rules using [custom webpack config](https://storybook.js.org/configurations/custom-webpack-config/#full-control-mode--default).

**Comment by felipe-norato** [comment]
@Quramy Thanks
I saw that and I agree to using the original set custom rules
:smiley:
